all:
	gcc -o partition_problem partition_problem.c kernel.c -lm -O2

g:
	./partition_problem g < ./in/input_1.txt > ./output/output_g_1.txt
	./partition_problem g < ./in/input_2.txt > ./output/output_g_2.txt
	./partition_problem g < ./in/input_3.txt > ./output/output_g_3.txt
	./partition_problem g < ./in/input_4.txt > ./output/output_g_4.txt
	./partition_problem g < ./in/input_5.txt > ./output/output_g_5.txt
	./partition_problem g < ./in/input_6.txt > ./output/output_g_6.txt
dp1:
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt

	
dp2:
	./partition_problem dp < ./in/input_2.txt > ./output/output_dp_2.txt
	

dp3:
	./partition_problem dp < ./in/input_3.txt > ./output/output_dp_3.txt

dp4:
	./partition_problem dp < ./in/input_4.txt > ./output/output_dp_4.txt

dp5:
	./partition_problem dp < ./in/input_5.txt > ./output/output_dp_5.txt

dp6:
	./partition_problem dp < ./in/input_6.txt > ./output/output_dp_6.txt

dp:

	./partition_problem dp < ./in/input_1.txt > ./output/output_dp_1.txt
	./partition_problem dp < ./in/input_2.txt > ./output/output_dp_2.txt
	./partition_problem dp < ./in/input_3.txt > ./output/output_dp_3.txt
	./partition_problem dp < ./in/input_4.txt > ./output/output_dp_4.txt
	./partition_problem dp < ./in/input_5.txt > ./output/output_dp_5.txt
	./partition_problem dp < ./in/input_6.txt > ./output/output_dp_6.txt

	
competition:
	./partition_problem dp < ./in/input_5.txt > ./output/output_dp_5.txt